In [1]:
import numpy as np

DataTypes & Attributes

In [2]:
a1 = np.array([1,2,3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3], [4,5,6.5]])

a3 = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
               
              [[10, 11, 12],
              [13, 14, 15],
               [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [15]:
# Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## 2. Creating Arrays

In [16]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int64')

In [18]:
ones = np.ones([2, 3])

In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [22]:
zeros = np.zeros([2,3])

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0, 10, 2)

In [25]:
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array = np.random.randint(0, 10, size=(3, 5))

In [27]:
random_array

array([[9, 0, 0, 0, 0],
       [2, 1, 4, 5, 0],
       [6, 9, 7, 9, 5]], dtype=int32)

In [28]:
random_array.size

15

In [29]:
random_array.shape

(3, 5)

In [30]:
random_array_2 = np.random.random((5, 3))

In [31]:
random_array_2

array([[0.22743765, 0.35444872, 0.36262092],
       [0.92427633, 0.93622474, 0.0578308 ],
       [0.51383888, 0.86198553, 0.46135663],
       [0.09071088, 0.17968076, 0.06096984],
       [0.66186377, 0.23948892, 0.46463073]])

In [32]:
random_array_2.shape

(5, 3)

In [33]:
random_array_3 = np.random.rand(5,3)

In [34]:
random_array_3

array([[0.41176374, 0.40000241, 0.12423754],
       [0.63761224, 0.54270293, 0.5654208 ],
       [0.99010861, 0.14907664, 0.92497033],
       [0.32244818, 0.00851836, 0.32093914],
       [0.80650967, 0.83727968, 0.49810839]])

In [35]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [36]:
random_array_4.shape

(5, 3)

In [37]:
np.random.seed(7)
random_array_5 = np.random.randint(10, size=(5, 3))
random_array_5

array([[4, 9, 6],
       [3, 3, 7],
       [7, 9, 7],
       [8, 9, 8],
       [7, 6, 4]], dtype=int32)

## Viewing arrays and Matrices

In [38]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [39]:
a1

array([1, 2, 3])

In [40]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [41]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [42]:
a1[0]

np.int64(1)

In [43]:
a2[0]

array([1., 2., 3.])

In [44]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
a3[:2,:2, :2]


array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [46]:
a3.shape

(2, 3, 3)

In [47]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[0, 7, 0, 7, 6],
         [3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7]],

        [[3, 3, 8, 3, 0],
         [1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4]],

        [[3, 1, 3, 1, 3],
         [4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0]]],


       [[[9, 9, 3, 4, 5],
         [3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5]],

        [[7, 1, 5, 4, 4],
         [9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6]],

        [[9, 8, 6, 5, 9],
         [7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4]]]], dtype=int32)

In [48]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [49]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[0, 7, 0, 7],
         [3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9]],

        [[3, 3, 8, 3],
         [1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5]],

        [[3, 1, 3, 1],
         [4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3]]],


       [[[9, 9, 3, 4],
         [3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6]],

        [[7, 1, 5, 4],
         [9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1]],

        [[9, 8, 6, 5],
         [7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9]]]], dtype=int32)

In [50]:
a5 = np.random.randint(5, size=(2, 3, 3))
a5

array([[[2, 1, 3],
        [3, 2, 4],
        [0, 3, 0]],

       [[1, 0, 4],
        [3, 1, 2],
        [0, 2, 0]]], dtype=int32)

In [51]:
a5[:, :, :2]

array([[[2, 1],
        [3, 2],
        [0, 3]],

       [[1, 0],
        [3, 1],
        [0, 2]]], dtype=int32)

## 4. Manipulating and Comparing Arrays

### Arithmetic

In [52]:
a1

array([1, 2, 3])

In [53]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [54]:
a1 + ones

array([2., 3., 4.])

In [55]:
a1 - ones

array([0., 1., 2.])

In [56]:
a1 * ones

array([1., 2., 3.])

In [57]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [58]:
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 19.5]])

In [59]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [60]:
a1 / ones

array([1., 2., 3.])

In [61]:
a2 / a1

array([[1.        , 1.        , 1.        ],
       [4.        , 2.5       , 2.16666667]])

In [62]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [63]:
a2 ** 2

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [64]:
np.square(a2)

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [65]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

### Aggregation
Aggregation = Performing the same operation on a number of things

In [66]:
listy_list = [1,2,3]
type(listy_list)

list

sum(listy_list)

In [67]:
a1

array([1, 2, 3])

In [68]:
sum(a1)

np.int64(6)

In [69]:
np.sum(a1)

np.int64(6)

Use Python's methods (`sum()`) on Python datatypes and use Numpy's methods on Numpy arrays (np.sum()).

In [70]:
massive_arrays = np.random.random(10000)
massive_arrays.size

10000

In [71]:
massive_arrays[:10]

array([0.22057967, 0.55054305, 0.52259111, 0.48755248, 0.26303148,
       0.52728579, 0.98446573, 0.62342345, 0.62955693, 0.9099729 ])

In [72]:
%timeit sum(massive_arrays)
%timeit np.sum(massive_arrays)

1.19 ms ± 29.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
12.6 μs ± 383 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [73]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [74]:
np.mean(a2)

np.float64(3.5833333333333335)

In [75]:
np.max(a2)

np.float64(6.5)

In [76]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [77]:
np.var(high_var_array), np.var(low_var_array)

(np.float64(4296133.472222221), np.float64(8.0))

In [78]:
np.std(high_var_array), np.std(low_var_array)

(np.float64(2072.711623024829), np.float64(2.8284271247461903))

### Reshape and Transposing

In [79]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [80]:
a2.shape

(2, 3)

In [81]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [82]:
a3.shape

(2, 3, 3)

In [83]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [84]:
a2.reshape(2,3, 1)

array([[[1. ],
        [2. ],
        [3. ]],

       [[4. ],
        [5. ],
        [6.5]]])

In [85]:
a2_reshape = a2.reshape(2,3,1)

In [86]:
a2_reshape

array([[[1. ],
        [2. ],
        [3. ]],

       [[4. ],
        [5. ],
        [6.5]]])

In [87]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 21. ,  24. ,  27. ]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [89]:
# Transpose
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3. , 6.5]])

In [90]:
a2.T.shape

(3, 2)

In [91]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [92]:
a2.shape

(2, 3)

## Dot Product

In [93]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5,3))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [94]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [95]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [96]:
# Element-wise multiplication (Hadamard product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]], dtype=int32)

In [97]:
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [98]:
mat3 = mat1.T

In [99]:
mat3

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]], dtype=int32)

In [100]:
mat3.shape

(3, 5)

In [101]:
mat2.shape

(5, 3)

In [103]:
np.dot(mat3, mat2).shape

(3, 3)

## Dot product example (nut butter sales)

In [108]:
np.random.seed(0)
# Number of jars sold
sales_amount = np.random.randint(20, size=(5, 3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [109]:
# Create Weekly Sales DataFrame
weekly_sales = pd.DataFrame(sales_amount, index=["Mon", "Tues", "Wed", "Thurs", "Fri"], columns=["Almond butter", "Peanut butter", "Cashew butter"])

In [110]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [111]:
# Create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [115]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"], columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [118]:
prices.shape, sales_amount.shape

((3,), (5, 3))

In [119]:
total_sales = prices.dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [122]:
# Create Daily Sales
weekly_sales["Total ($)"] = total_sales.T

In [123]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

## Comparison Operators

In [124]:
a1

array([1, 2, 3])

In [125]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [126]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

## Sorting Array

In [128]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]], dtype=int32)

In [129]:
np.sort(random_array)

array([[1, 3, 3, 3, 8],
       [0, 1, 7, 9, 9],
       [0, 2, 3, 4, 7]], dtype=int32)

In [130]:
np.argsort(random_array)

array([[1, 2, 3, 4, 0],
       [1, 2, 0, 3, 4],
       [0, 4, 3, 1, 2]])

In [131]:
np.argmin(random_array)

np.int64(6)

## Practical Example - Numpy in Action !!!!

In [138]:
<img src="images/panda.png"/>

SyntaxError: invalid syntax (2701874586.py, line 1)

In [ ]:
# turn an image into a Numpy array
from matplotlib.image import imread