In [1]:
import numpy as np

In [2]:
# Creating Numpy Arrays
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [3]:
arr3 = np.zeros((2, 3))

In [4]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr4 = np.ones((2, 3))

In [6]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
#Pseudo-random numbers
# np.random.seed
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 7, 7],
       [3, 9, 6],
       [2, 5, 3],
       [5, 1, 1],
       [3, 0, 1]], dtype=int32)

In [8]:
random_array_4.shape

(5, 3)

In [9]:
random_array_4.size

15

In [10]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

# Viewing array and Matrices

In [12]:
np.unique(random_array_4)

array([0, 1, 2, 3, 5, 6, 7, 9], dtype=int32)

In [13]:
arr_1d = np.array([10, 20, 30, 40, 50])

arr_1d

array([10, 20, 30, 40, 50])

In [14]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr_3d = np.array([[[1, 2], [4, 5]], [[5, 6], [7, 8]]])
arr_3d

array([[[1, 2],
        [4, 5]],

       [[5, 6],
        [7, 8]]])

In [18]:
arr_1d.ndim, arr_2d.ndim, arr_3d.ndim

(1, 2, 3)

In [19]:
arr_1d.size, arr_2d.size, arr_3d.size

(5, 6, 8)

In [20]:
arr_1d.dtype, arr_2d.dtype, arr_3d.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [21]:
arr_1d.itemsize, arr_2d.itemsize, arr_3d.itemsize

(8, 8, 8)

In [22]:
arr_1d.nbytes, arr_2d.nbytes, arr_3d.nbytes

(40, 48, 64)

In [25]:
arr_1d[0], arr_1d[2], arr_1d[-1]

(np.int64(10), np.int64(30), np.int64(50))

In [27]:
arr_1d

array([10, 20, 30, 40, 50])

In [26]:
arr_1d[1:4], arr_1d[:3], arr_1d[::2]

(array([20, 30, 40]), array([10, 20, 30]), array([10, 30, 50]))

In [28]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr_2d[0, 1], arr_2d[1,0]

(np.int64(2), np.int64(4))

In [31]:
arr_2d[0, :], arr_2d[:, 1]

(array([1, 2, 3]), array([2, 5]))

## 4. Manipulating & Comparing Arrays

In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [33]:
a + b

array([5, 7, 9])

In [34]:
b - a

array([3, 3, 3])

In [35]:
b/a

array([4. , 2.5, 2. ])

In [36]:
a ** 2

array([1, 4, 9])

In [37]:
b % a

array([0, 1, 0])

## 5. Aggregations

In [38]:
arr = np.array([1, 2, 3, 4, 5])

In [39]:
np.sum(arr), np.mean(arr), np.median(arr), np.min(arr), np.max(arr), np.std(arr), np.var(arr)

(np.int64(15),
 np.float64(3.0),
 np.float64(3.0),
 np.int64(1),
 np.int64(5),
 np.float64(1.4142135623730951),
 np.float64(2.0))