In [1]:
import numpy as np

In [2]:
# Creating Numpy Arrays
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [3]:
arr3 = np.zeros((2, 3))

In [4]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr4 = np.ones((2, 3))

In [6]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
#Pseudo-random numbers
# np.random.seed
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 7, 7],
       [3, 9, 6],
       [2, 5, 3],
       [5, 1, 1],
       [3, 0, 1]], dtype=int32)

In [8]:
random_array_4.shape

(5, 3)

In [9]:
random_array_4.size

15

In [10]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])